CREATE DATABASE walmart_analytics;
USE walmart_analytics;

CREATE TABLE walmart_sales (
    Store INT,
    Dept INT,
    Date DATE,
    Weekly_Sales DOUBLE,
    IsHoliday INT
);

#Data Exploration Queries

SELECT COUNT(*) FROM walmart_sales;
SELECT COUNT(DISTINCT Store) FROM walmart_sales;
SELECT COUNT(DISTINCT Dept) FROM walmart_sales;
SELECT MIN(Date), MAX(Date) FROM walmart_sales;
select * from walmart_sales limit 10;

#KPIs
-- TOTAL REVENUE
SELECT ROUND(SUM(WEEKLY_SALES),2)  AS `TOTAL REVENUE`
FROM WALMART_SALES;

-- AVERAGE WEEKLY SALES
SELECT ROUND(AVG(WEEKLY_SALES),2) AS `AVG_WEEKLY_SALES`
FROM WALMART_SALES  ;

-- TOTAL TRANSACTIONS
SELECT COUNT(*) AS `TOTAL TRANSACTIONS`
FROM WALMART_SALES;

# TREND ANALYSIS 

-- MONTHLY SALES TREND
SELECT DATE_FORMAT(DATE,'%Y-%m') AS MONTH,
ROUND(SUM(WEEKLY_SALES),2) AS MONTHLY_REVENUE
FROM WALMART_SALES 
GROUP BY DATE_FORMAT(DATE,'%Y-%m')
ORDER BY MONTH ;

-- YEARLY TREND ANALYSIS 
SELECT YEAR(DATE) AS YEAR,
ROUND(SUM(WEEKLY_SALES),2) AS YEARLY_REVENUE
FROM WALMART_SALES
GROUP BY YEAR(DATE)
ORDER BY YEAR;

# TOP AND BOTTOM PERFORMING STORES

-- TOP 10 PERFORMING STORES
SELECT STORE ,
ROUND(SUM(WEEKLY_SALES),2) AS REVENUE
FROM WALMART_SALES
GROUP BY STORE
ORDER BY REVENUE DESC
LIMIT 10;

-- BOTTOM 10 PERFORMING STORES
SELECT STORE ,
ROUND(SUM(WEEKLY_SALES),2) AS REVENUE
FROM WALMART_SALES
GROUP BY STORE
ORDER BY REVENUE ASC
LIMIT 10;

# TOP AND BOTTOM PERFORMING DEPARTMENTS

SELECT DEPT ,
ROUND(SUM(WEEKLY_SALES),2) AS REVENUE
FROM WALMART_SALES
GROUP BY DEPT
ORDER BY REVENUE DESC
LIMIT 10;

SELECT DEPT ,
ROUND(SUM(WEEKLY_SALES),2) AS REVENUE
FROM WALMART_SALES
GROUP BY DEPT
ORDER BY REVENUE ASC
LIMIT 10;

# HOLIDAY IMPACT ANALYSIS 
SELECT ISHOLIDAY ,
ROUND(SUM(WEEKLY_SALES),2) AS REVENUE
FROM WALMART_SALES
GROUP BY ISHOLIDAY;

# MONTLY GROWTH PERCENTAGE
SELECT 
    DATE_FORMAT(DATE,'%Y-%m') AS MONTH,
    ROUND(SUM(Weekly_Sales),2) AS MONTHLY_REV,
    CONCAT(ROUND(
        (SUM(Weekly_Sales) - 
        LAG(SUM(Weekly_Sales)) OVER (ORDER BY DATE_FORMAT(Date,'%Y-%m')))
        /
        LAG(SUM(Weekly_Sales)) OVER (ORDER BY DATE_FORMAT(Date,'%Y-%m'))
        * 100,2),"%") AS GROWTH_PERCENTAGE
FROM WALMART_SALES
GROUP BY MONTH;

#TOP REVENUE CONTRIBUTING STORE
SELECT 
    STORE,
    ROUND(SUM(WEEKLY_SALES),2) AS REVENUE,
    CONCAT(ROUND(
        SUM(WEEKLY_SALES) * 100.0 / 
        (SELECT SUM(WEEKLY_SALES) FROM WALMART_SALES),2),"%") AS CONTRIBUTION_PERCENTAGE
FROM WALMART_SALES
GROUP BY STORE
ORDER BY REVENUE DESC
LIMIT 10;
